require_relative '../app/models/comedian.rb'
require_relative '../app/models/special.rb'

Comedian.destroy_all
john_m = Comedian.create(name: "John Mulaney", age: 36, city: "Chicago, IL")
jerry = Comedian.create(name: "Jerry Seinfeld", age: 64, city: "New York City, NY")
pete = Comedian.create(name: "Pete Holmes", age: 39, city: "Los Angeles, CA")
mike = Comedian.create(name: "Mike Birbiglia", age: 55, city: "Brookline, MA")
jon = Comedian.create(name: "Jon Stewart", age: 56, city: "Lawrenceville, NJ")
john_o = Comedian.create(name: "John Oliver", age: 41, city: "Birmingham, England")
hannibal = Comedian.create(name: "Hannibal Buress", age: 35, city: "Chicago, IL")
tig = Comedian.create(name: "Tig Notaro", age: 47, city: "Jackson, MS")
ryan = Comedian.create(name: "Ryan Hamilton", age: 42, city: "Ashton, ID")
hasan = Comedian.create(name: "Hasan Minhaj", age: 33, city: "Davis, CA")
neal = Comedian.create(name: "Neal Brennan", age: 45, city: "Villanova, PA")
dave = Comedian.create(name: "Dave Chappelle", age: 45, city: "Washington D.C.")
mark = Comedian.create(name: "Mark Normand", age: 34, city: "New Orleans, LA")

Special.destroy_all
john_m.specials.create(name: "New In Town")
john_m.specials.create(name: "The Comeback Kid")
john_m.specials.create(name: "Kid Gorgeous at Radio City")
jerry.specials.create(name: "Jerry Before Seinfeld")
jerry.specials.create(name: "I'm Telling You For The Last Time")
jerry.specials.create(name: "Stand Up Confidential")
pete.specials.create(name: "Dirty Clean")
pete.specials.create(name: "Faces and Sounds")
mike.specials.create(name: "Thank God for Jokes")
mike.specials.create(name: "What I Should Have Said Was Nothing")
mike.specials.create(name: "Mike Birbiglia's Secret Public Journal")
jon.specials.create(name: "Unleavened")
john_o.specials.create(name: "Terrifying Times")
john_o.specials.create(name: "Decline of the American Empire")
hannibal.specials.create(name: "Comedy Camisado")
hannibal.specials.create(name: "Animal Furnace")
tig.specials.create(name: "Happy to Be Here")
tig.specials.create(name: "Boyish Girl Interrupted")
ryan.specials.create(name: "Happy Face")
hasan.specials.create(name: "Homecoming King")
neal.specials.create(name: "3 Mics")
dave.specials.create(name: "Equanimity")
dave.specials.create(name: "The Bird Revelation")
dave.specials.create(name: "Killin' Them Softly")
mark.specials.create(name: "SXSW Comedy with W. Kamau Bell")
