require_relative '../app/models/comedian.rb'
require_relative '../app/models/special.rb'

Comedian.destroy_all
john_m = Comedian.create(name: "John Mulaney", age: 36, city: "Chicago, IL")
jerry = Comedian.create(name: "Jerry Seinfeld", age: 64, city: "New York City, NY")
pete = Comedian.create(name: "Pete Holmes", age: 39, city: "Los Angeles, CA")
mike = Comedian.create(name: "Mike Birbiglia", age: 55, city: "Brookline, MA")
jon = Comedian.create(name: "Jon Stewart", age: 56, city: "Lawrenceville, NJ")
john_o = Comedian.create(name: "John Oliver", age: 41, city: "Birmingham, England")
hannibal = Comedian.create(name: "Hannibal Buress", age: 35, city: "Chicago, IL")
tig = Comedian.create(name: "Tig Notaro", age: 47, city: "Jackson, MS")
ryan = Comedian.create(name: "Ryan Hamilton", age: 42, city: "Ashton, ID")
hasan = Comedian.create(name: "Hasan Minhaj", age: 33, city: "Davis, CA")
neal = Comedian.create(name: "Neal Brennan", age: 45, city: "Villanova, PA")
dave = Comedian.create(name: "Dave Chappelle", age: 45, city: "Washington D.C.")
mark = Comedian.create(name: "Mark Normand", age: 34, city: "New Orleans, LA")

Special.destroy_all
john_m.specials.create(name: "New In Town", run_time: 60)
john_m.specials.create(name: "The Comeback Kid", run_time: 62)
john_m.specials.create(name: "Kid Gorgeous at Radio City", run_time: 65)
jerry.specials.create(name: "Jerry Before Seinfeld", run_time: 62, image_url: "https://m.media-amazon.com/images/M/MV5BOTc2N2I0Y2UtOTgyYy00MTU3LTk1YzItZGIwMDcxY2JkMGQzXkEyXkFqcGdeQXVyMjQzNzk2ODk@._V1_UY268_CR1,0,182,268_AL_.jpg")
jerry.specials.create(name: "I'm Telling You For The Last Time", run_time: 75)
jerry.specials.create(name: "Stand Up Confidential", run_time: 55)
pete.specials.create(name: "Dirty Clean", run_time: 57)
pete.specials.create(name: "Faces and Sounds", run_time: 57)
mike.specials.create(name: "Thank God for Jokes", run_time: 85)
mike.specials.create(name: "What I Should Have Said Was Nothing", run_time: 60)
mike.specials.create(name: "Mike Birbiglia's Secret Public Journal", run_time: 60)
jon.specials.create(name: "Unleavened", run_time: 52)
john_o.specials.create(name: "Terrifying Times", run_time: 60)
hannibal.specials.create(name: "Comedy Camisado", run_time: 83)
hannibal.specials.create(name: "Animal Furnace", run_time: 65)
tig.specials.create(name: "Happy to Be Here", run_time: 58)
tig.specials.create(name: "Boyish Girl Interrupted", run_time: 55)
ryan.specials.create(name: "Happy Face", run_time: 55)
hasan.specials.create(name: "Homecoming King", run_time: 72)
neal.specials.create(name: "3 Mics", run_time: 65)
dave.specials.create(name: "Equanimity", run_time: 60)
dave.specials.create(name: "The Bird Revelation", run_time: 49)
dave.specials.create(name: "Killin' Them Softly", run_time: 57)
mark.specials.create(name: "SXSW Comedy with W. Kamau Bell", run_time: 158)
