require_relative '../app/models/comedian.rb'
require_relative '../app/models/special.rb'

Comedian.destroy_all
Comedian.create(name: "John Mulaney", age: 36, city: "Chicago, IL")
Comedian.create(name: "Jerry Seinfeld", age: 64, city: "New York City, NY")
Comedian.create(name: "Pete Holmes", age: 39, city: "Los Angeles, CA")
Comedian.create(name: "Mike Birbiglia", age: 55, city: "Brookline, MA")
Comedian.create(name: "Jon Stewart", age: 56, city: "Lawrenceville, NJ")
Comedian.create(name: "John Oliver", age: 41, city: "Birmingham, England")
Comedian.create(name: "Hannibal Buress", age: 35, city: "Chicago, IL")
Comedian.create(name: "Tig Notaro", age: 47, city: "Jackson, MS")
Comedian.create(name: "Ryan Hamilton", age: 42, city: "Ashton, ID")
Comedian.create(name: "Hasan Minhaj", age: 33, city: "Davis, CA")
Comedian.create(name: "Neal Brennan", age: 45, city: "Villanova, PA")
Comedian.create(name: "Dave Chappelle", age: 45, city: "Washington D.C.")
Comedian.create(name: "Mark Normand", age: 34, city: "New Orleans, LA")

Special.destroy_all
Special.create(name: "New In Town", comedian_id: 1)
Special.create(name: "The Comeback Kid", comedian_id: 1)
Special.create(name: "Kid Gorgeous at Radio City", comedian_id: 1)
Special.create(name: "Jerry Before Seinfeld", comedian_id: 2)
Special.create(name: "I'm Telling You For The Last Time", comedian_id: 2)
Special.create(name: "Stand Up Confidential", comedian_id: 2)
Special.create(name: "Dirty Clean", comedian_id: 3)
Special.create(name: "Faces and Sounds", comedian_id: 3)
Special.create(name: "Thank God for Jokes", comedian_id: 4)
Special.create(name: "What I Should Have Said Was Nothing", comedian_id: 4)
Special.create(name: "Mike Birbiglia's Secret Public Journal", comedian_id: 4)
Special.create(name: "Unleavened", comedian_id: 5)
Special.create(name: "Terrifying Times", comedian_id: 6)
Special.create(name: "Decline of the American Empire", comedian_id: 6)
Special.create(name: "Comedy Camisado", comedian_id: 7)
Special.create(name: "Animal Furnace", comedian_id: 7)
Special.create(name: "Happy to Be Here", comedian_id: 8)
Special.create(name: "Boyish Girl Interrupted", comedian_id: 8)
Special.create(name: "Happy Face", comedian_id: 9)
Special.create(name: "Homecoming King", comedian_id: 10)
Special.create(name: "3 Mics", comedian_id: 11)
Special.create(name: "Equanimity", comedian_id: 12)
Special.create(name: "The Bird Revelation", comedian_id: 12)
Special.create(name: "Killin' Them Softly", comedian_id: 12)
Special.create(name: "SXSW Comedy with W. Kamau Bell", comedian_id: 13)
